---
env: dev

#pipeline:
#  backend:
#    url:  'https://{{ $.Values.global.appname }}-{{ $.Release.Namespace }}.{{ $.Values.global.cluster.baseDomain }}/api/v1'

global:
  appname: demo-app

  backend:
    name: demo-backend
    port: 8080
    imageRepo: quay.io/natelove/demo:latest
  labels:
    - key: helm.sh/chart
      value: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
    - key: app.kubernetes.io/managed-by
      value: "{{ $.Release.Service }}"
    - key: app.kubernetes.io/instance
      value: "{{ $.Release.Name }}"
    - key: app.kubernetes.io/version
      value: "{{ $.Chart.AppVersion }}"
  cluster:
    baseDomain: apps.shared-na4.na4.openshift.opentlc.com
