---
{{- with .Values.global.backend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Values.global.appname }}
    name: {{ .name }}
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
  name: {{ .name }}
spec:
  replicas: {{ .replicas | default "1" }}
  selector:
    matchLabels:
      app: {{ $.Values.global.appname }}
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
  template:
    metadata:
      labels:
        app: {{ $.Values.global.appname }}
        name: {{ .name }}
      name: {{ .name }}-deploy
    spec:
      containers:
      - name: {{ .name }}
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: {{ .contextPath }}
        - name: JAVA_ARGS
          value: --spring.profiles.active={{ .env }}
        image: {{ .image }}
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: {{ .liveProbe }}
            port: {{ .port }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: {{ .readyProbe }}
            port: {{ .port }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: {{ .port }}
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


{{- end -}}
