
{{- with .Values.global.backend }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ $.Values.global.appname }}
    name: {{ .name }}
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
  name: {{ .name }}
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: {{ .imageRepo}}
      importPolicy: { }
      referencePolicy:
        type: Source
{{- end -}}